---
- name: Creating an EC2 Instance with Creating a VPC and Subnet Id
  hosts: localhost
  tasks:
    - name: Create a Security Group  
      amazon.aws.ec2_security_group:
        name: "Ansible-Test-Security-Group"
        description: "Ansible-Testing"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all on port 80"
      register: security_group
    
    - name: "Artifact the Security Group var"
      ansible.builtin.set_stats:
        data:
          security_group: "{{security_group}}"
